### ISSUE TITLE
Improve golang report card

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#176]
**What steps did you take and what happened:**
Goreportcard for our repo identified few lint issues. It would be good if we can fix them and improve the score.

**What did you expect to happen:**
More than 95% for all the lint sections

**Anything else you would like to add:**
Report card - https://goreportcard.com/report/github.com/vmware-tanzu/cluster-api-provider-bringyourownhost

**Comment by pshail** [comment]
@anusha94 Example of pesky automation, this issue actually has multiple things to tackle and since I tagged it in one of the PR that partially fixes this, it got auto closed 🤷‍♂️ . I will open another one for remaining issue(s(
