### ISSUE TITLE
Create Release Targets

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#180]
Create make targets that will be used for release activities

- [x] host-agent-binary
- [x] infrastructure-components.yaml
- [x] cluster-template.yaml
- [x] metadata.yaml
- ~~[ ] byoh controller image (build and push)~~
- ~~[ ] imgpkg k8s bundle (build and push)~~

**Comment by jamiemonserrate** [comment]
Can we ensure that when we publish the `host-agent` binary, it is an executable binary? (that is the exec bit is set)

**Comment by anusha94** [comment]
fyi - I am working on build and push controller image task

**Comment by anusha94** [comment]
In BYOH, currently all images and installer bundles are pushed to Harbor registry. To push to this registry, we need to be in VMware's corporate network. Automating the push via GitHub Action's runner may become complicated as we will have to directly hit the registry's IP and store this IP as a secret.
We will migrate to k-sigs soon and hope to leverage Prow's capability to push to gcr.io just like other providers. Closing this issue for now.

**Comment by anusha94** [comment]
> Can we ensure that when we publish the `host-agent` binary, it is an executable binary? (that is the exec bit is set)

@jamiemonserrate when we build the binary, it is indeed executable. But when we download the binary, the exec bit is not set. Same goes for any other binary we download. See [clusterctl install](https://cluster-api.sigs.k8s.io/user/quick-start.html?highlight=clusterctl#install-clusterctl) or [kubectl install](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-on-linux)

TIL - https://unix.stackexchange.com/questions/82578/why-is-that-when-i-download-a-binary-from-the-web-it-doesnt-have-executable-per

Let me know if you had something else to try out. Otherwise, we are pretty much done with this issue.

**Comment by jamiemonserrate** [comment]
That makes sense. Not sure what I was thinking when I wrote 

> Can we ensure that when we publish the host-agent binary, it is an executable binary? (that is the exec bit is set). 

Fair enough.
