### ISSUE TITLE
Document how to assign ControlPlaneEndpoint

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#199]
It will be good to add information around how to assign `ControlPlaneEndpoint IP` in the getting started document - 
We only state that CP Endpoint should be an IP in the subnet but not in the DHCP range. Refer to [create workload cluster](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/getting_started.md#create-workload-cluster)

**Comment by NilanjanDaw** [comment]
I can take this one
