### ISSUE TITLE
Add clusterctl provider label to BYOH infrastructure components

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#212]
`Clusterctl` integration requires provider label(`clusterctl.cluster.x-k8s.io/provider`) to be available with all `BYOH` infrastructure components. Details [here](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#labels).

This label `cluster.x-k8s.io/provider: "infrastructure-byoh"` has to be added here in [kustomization.yaml](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/config/default/kustomization.yaml#L12) and validate the same via `make publish-infra-yaml`.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by anusha94** [comment]
@himanshu007-creator Thank you! I have assigned the issue to you. Let me know if you need any help 🙂

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Thank you! I have assigned the issue to you. Let me know if you need any help 🙂

Hey!
I am done with the addition in <code>kustomization.yaml</code>. But when i run <code>make manifests</code> command i got error <code>make ✖ ERR  not found: make-##</code>
I ran <code>make manifests --debug </code> and got the following logs

![2021-11-11](https://user-images.githubusercontent.com/65963997/141299909-61ad6f86-25ef-46e8-8698-d15df8333698.png)

**Comment by anusha94** [comment]
Hey @himanshu007-creator , So the make target is trying to download `controller-gen` locally. Are you running this on a windows env? I'm not sure of the behavior. @dharmjit, Do you know?

You can also open a draft PR and we can look at your changes and try to debug from there.
Thanks!

**Comment by dharmjit** [comment]
Hi @himanshu007-creator, As @anusha94 mentioned, please raise a draft PR with only the change in `kustomization.yaml` fille. Thanks.
