### ISSUE TITLE
Add repo description

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/cluster-api-provider-bringyourownhost#233]
The repo could use a repo description so that people can quickly read a one-liner on the project. This would also show up in the repo previews I believe when sharing links on different mediums

![Screenshot 2021-11-11 at 3 24 54 PM](https://user-images.githubusercontent.com/12808424/141277689-f121e16b-bb3e-4e4e-a393-dc62fdf612d4.png)

Link previews of GitHub repos on slack -

![Screenshot 2021-11-11 at 3 27 08 PM](https://user-images.githubusercontent.com/12808424/141277872-1c6a1bf1-17e2-436b-8a49-40ef692a9eba.png)

**Comment by shamsher31** [comment]
@karuppiah7890 Thanks for the suggestion. Also added a few tags. And we need more stars 

![Screenshot 2021-11-11 at 4 24 58 PM](https://user-images.githubusercontent.com/2920003/141286620-c0253be4-8450-4fe3-ba13-5b25c3fdddaa.png)


![Screenshot 2021-11-11 at 4 23 44 PM](https://user-images.githubusercontent.com/2920003/141286634-cfaa6de2-289f-4f45-b031-d0e678a927e4.png)
