### ISSUE TITLE
Add demo video of how BYOH works

### ISSUE THREAD

**Issue by karuppiah7890** [vmware-tanzu/cluster-api-provider-bringyourownhost#234]
I have noticed some short demo videos on how BYOH works, I think it would be beneficial for new folks landing on the project (repo, readme) to see similar short demo videos to get a quick glimpse of BYOH. These video(s) could be linked in the repo readme

**Comment by pshail** [comment]
@anusha94 if we keep the videos in the main repo we should make it lower in size, else pull/sync overhead will be more - thoughts?

**Comment by karuppiah7890** [comment]
The video could be on YouTube and linked in the readme

**Comment by anusha94** [comment]
@pshail @karuppiah7890 
Saw that [TCE is using a gif](https://github.com/vmware-tanzu/community-edition/blob/main/README.md) to provide an [overview](https://github.com/vmware-tanzu/community-edition/blob/7f931418045e1834d60ed37887a018e17ddee68c/README.md?plain=1#L18). Could be a good option.

**Comment by karuppiah7890** [comment]
Yup, that's a good option too

So, we have -
- video in repo and linked in readme
- video in YouTube or similar platform and linked in readme
- gif in readme
- asciinema or similar terminal recording and linked in readme

Note that gifs can be big in size, especially when the video they are trying to show in the form of moving image is long
