### ISSUE TITLE
Only run [PR-Blocking] tests for PRs

### ISSUE THREAD

**Issue by jamiemonserrate** [vmware-tanzu/cluster-api-provider-bringyourownhost#242]
**Describe the solution you'd like**
We should only run the `[PR-Blocking]` tests as part of each PR. This will help improve the feedback time to folks raising PRs. 

We should also have the ability to run the rest of the suite on demand. Preferably via github `/commands`

**Comment by karuppiah7890** [comment]
For K8s Prow like `/command` in GitHub, you can checkout https://github.com/jpmcb/prow-github-actions which is something we use for labelling issues primarily. You could checkout how it can be used to run test suits on GitHub Actions

**Comment by anusha94** [comment]
Thanks @karuppiah7890 for the pointer. @shamsher31 , is this something we can investigate for this project?

**Comment by shamsher31** [comment]
> For K8s Prow like `/command` in GitHub, you could checkout https://github.com/jpmcb/prow-github-actions which is something we use for labelling issues primarily. You could checkout how it can be used to run test suites on GitHub Actions

This looks great. Thanks for sharing @karuppiah7890 .

> @shamsher31 , is this something we can investigate for this project?

We can use it for now until Prow is available across Tanzu projects.
