### ISSUE TITLE
Fix go lint issues highlighted in Go report Card 

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#250]
Go Report Card [Results](https://goreportcard.com/report/github.com/vmware-tanzu/cluster-api-provider-bringyourownhost) for go lint is only 56%.  Most of these are for exported fields/methods not having comments. We need to fix these lint issues.

**Comment by raunaksingwi** [comment]
I can take this one

**Comment by jayesh-srivastava** [comment]
Hi. Was wondering if @raunaksingwi is still working on this issue. If not then I would like to work on this.

**Comment by anusha94** [comment]
/unassign @raunaksingwi 
/assign @jayesh-srivastava 

Thanks for picking it up @jayesh-srivastava !

**Comment by anusha94** [comment]
Hey @jayesh-srivastava !
Let us know if you need any assistance.

**Comment by jayesh-srivastava** [comment]
Hi @anusha94 I was working on the issue. There are a lot of files that need modifications. I was thinking of making multiple PRs for different packages as it would be then easier to review. Any thoughts?

**Comment by anusha94** [comment]
@jayesh-srivastava 
That sounds good!

**Comment by jayesh-srivastava** [comment]
Also @anusha94 a lot of issues regarding this are related to structs and functions not having comments. I'll have to manually do this because there is no autofix for golint. How should I do this because to know what each structs and functions do, that is a nearly impossible task I guess.

`exported type ScriptExecutor should have comment or be unexported`

**Comment by anusha94** [comment]
@jayesh-srivastava that's a fair call-out. I haven't taken a loot at the lint errors myself. But from the issue description, it's indeed mostly comments.
I can create a task list for this issue for different categories of lint errors. Probably then it will be easier for you to work on a subset of these tasks? 
One of us on the byoh team can work on the missing comments.

**Comment by jayesh-srivastava** [comment]
@anusha94 That would work. I guess 99 percent of the issues are only comments. The ones which are not, I'll work and make the PR for it. The ones with the comment, maybe I can assist anyone on the byoh team who'll be working on this as the number of issues are a lot.
