### ISSUE TITLE
Add bundleLookupBaseRegistry, bundleLookupTag in cluster-template for ByoCluster

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#252]
With this #205 PR, we introduced 2 new fields `bundleLookupBaseRegistry`, `bundleLookupTag` for `ByoCluster` CRD. We need to define the same in `cluster-template.yaml` with their default /useful values.

We need to
- Add these fields to  [cluster-with-kcp.yaml](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-with-kcp.yaml#L25).
- Run `make cluster-templates` to update the cluster-template.yaml.

**Comment by anusha94** [comment]
Does it make sense to have a follow-up PR to add defaulting webhook for these fields?

**Comment by dharmjit** [comment]
> Does it make sense to have a follow-up ~PR~ issue to add defaulting webhook for these fields?

Just thinking about whether it makes sense to make this mandatory and provide the values in `cluster-template`, if that is the only way to consume it.
