### ISSUE TITLE
Pre-requisite check on Host-Agent start

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#254]
**What steps did you take and what happened:**
When using an `Ubuntu 20.04 VM` (with no additional installation of packages), applying the cluster-template proceeds until the k8s installation steps. It later complains of the missing installation required packages like `socat, ebtables, conntrack, ethtool`.

**What did you expect to happen:**
The requirements are already documented [here](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/local_dev.md#pre-requisites-1)
But if the user has not followed the steps to install these, host-agent on start should check for the pre-requisites (all required packages, os support etc.) and exit on failure.
This will save effort in registering a byohost that does not meet basic requirements and will go into a trying to `install / uninstall` reconcile loop. Manual intervention should not be needed.

**Comment by raunaksingwi** [comment]
I can take this one
