### ISSUE TITLE
Add --version flag to host agent binary

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#278]
It will be useful to provide a `--version` flag in the host-agent binary as we will have multiple agent releases so that the user can know the version being used. The output could consist of information in the below format

```
$ byoh-hostagent-linux-amd64 --version
Version: v0.1.0_alpha.2
BuildDate: 
...
```

**Comment by raunaksingwi** [comment]
I can take this one

**Comment by raunaksingwi** [comment]
Are we manually going to update the version (in the Makefile) or do we have to derive the version from some other variables like GOOS, GOARCH, etc?

**Comment by anusha94** [comment]
The build job will be triggered when we push a tag to the repo. See this job - 
https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/2a1aaaa4cae69640fdd71f7f1271961543e9fcd2/.github/workflows/draft-release.yaml#L23

You can use the `${{ github.ref_name }}` - this is going to be the agent binary version.
Does that answer?
