### ISSUE TITLE
Update the kube-vip to v0.4.0 

### ISSUE THREAD

**Issue by yixingjia** [vmware-tanzu/cluster-api-provider-bringyourownhost#282]
Currently, we use kube-vip version v0.3.5,  in v0.4.0 a group of new features have been added. Like IPVS load-balances, Auto-detect the interface for the VIP etc., which can help refactor the BYOH code. Currently, we have logic to detect the default interface on the BYOH host, after the update, we should be able to remove that code.

**Comment by thebsdbox** [comment]
I would wait until 0.4.1 as we (I) introduced a bug in that IPVS can come up before a control plane back end appears resulting in broken connectivity. (sorry)

**Comment by jayesh-srivastava** [comment]
@thebsdbox As v0.4.2 has been released too, should the update be to 0.4.1 or 0.4.2?

**Comment by sachinkumarsingh092** [comment]
This issue is similar to #461 and that is resolved by #462. Hence closing this.
