### ISSUE TITLE
Write unit / integration test for Paused Condition for ByoHost

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#338]
We do not have any test for this function - https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/1b485e7180727ea36bf24750d6a230f8a796e4f0/controllers/infrastructure/byomachine_controller.go#L383-L399

Write some unit or integration test to improve code coverage

**Comment by NilanjanDaw** [comment]
I can take a look into this one
