### ISSUE TITLE
Improve codecov for agent/cloudinit

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#339]
At the moment, we have 53% coverage for cloudinit. Identify more test cases to improve the coverage. To look at the detailed codecov report - https://app.codecov.io/gh/vmware-tanzu/cluster-api-provider-bringyourownhost

**Comment by NilanjanDaw** [comment]
Most of the files contain just boilerplate code and os library calls, which cannot really be unit/integration tested. Probably better to ignore them in the coverage report.
