### ISSUE TITLE
Improve codecov for agent/reconciler

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#340]
At the moment, we have 63% coverage for reconciler. Identify more test cases to improve the coverage. To look at the detailed codecov report - https://app.codecov.io/gh/vmware-tanzu/cluster-api-provider-bringyourownhost

Tasks -
- [x] uncomment unit test for uninstall flow https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/1fab38acf1d3a4fbe27ca147f694ee7f028bf712/agent/reconciler/reconciler_test.go#L431-L449
- [x] uncomment unit test for install flow https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/1fab38acf1d3a4fbe27ca147f694ee7f028bf712/agent/reconciler/reconciler_test.go#L178-L198
This will involve some changes to initializing installer in main.go and mocking installer's Install & Uninstall methods

- [x] #393

**Comment by anusha94** [comment]
This issue can be worked upon after completing #221 and #254

**Comment by NilanjanDaw** [comment]
Need an integration test reconciler to cover `bundle_downlaoder.go` especially `Download()` and `downloadByImgpkg()`

**Comment by NilanjanDaw** [comment]
All tasks are done.
