### ISSUE TITLE
Improve codecov for agent/installer

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#341]
At the moment, we have 69% coverage for installer. Identify more test cases to improve the coverage. To look at the detailed codecov report - https://app.codecov.io/gh/vmware-tanzu/cluster-api-provider-bringyourownhost

**Comment by NilanjanDaw** [comment]
I can take a stab at this

**Comment by NilanjanDaw** [comment]
`cli.go` is difficult to test and hard to mock. Recommending it to be added to the code-coverage report exclusion list [PR 344](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/issues/344#issuecomment-1026547102)
Some `bundle_downloader` paths need to be tested via integration tests through `reconciler` [PR 340](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/issues/340#issuecomment-1027681926).

Other paths have acceptable code coverage. Closing the issue.
