### ISSUE TITLE
Ignore auto-generated files and files containing boilerplate code in codecov report

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#344]
We have quite a bit of files that are auto-generated or contain just the boilerplate code which cannot really be unit/integration testable that can be captured in the codecov report.
This gives a false sense of underrated coverage which is not the exact indication of the overall value of  the repository. Codecov allows for ignoring such files and file paths. Refer https://docs.codecov.com/docs/ignoring-paths

Few files that can be ignored -
- https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/agent/main.go
- https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/controllers/infrastructure/byohost_controller.go
- https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/controllers/infrastructure/byomachinetemplate_controller.go

**Comment by NilanjanDaw** [comment]
Please consider adding https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/agent/installer/cli.go to the list.
