### ISSUE TITLE
Add namespace print column for BYOH CRDs

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#402]
When querying various `BYOH` CRDs as shown below, it would be useful to have a namespace print column if there are `BYOH` CRs in multiple namespaces. 
```
$ kubectl get byomachines
NAME                                     AGE
tkg-vc-byoh-antrea-control-plane-5gpw6   3h43m
tkg-vc-byoh-antrea-md-0-rpg76            3h39m

kubectl get byohosts
NAME     AGE
host1    3h45m
host10   3h45m
host2    3h45m
host3    3h45m
host4    3h45m

$ kubectl get byoclusters
NAME                 AGE
tkg-vc-byoh-antrea   3h44m
```

**Comment by shubham14bajpai** [comment]
Hi @dharmjit I am just curious as the CRDs are namespace scoped https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/fb51a6d7684ebf99bba0260c346d315da4e8fe0c/apis/infrastructure/v1beta1/byocluster_types.go#L56 

how will adding the namespace column be helpful?

**Comment by dharmjit** [comment]
Hi @shubham14bajpai Thanks for picking this issue. Currently for all `BYOH` CRs, `kubectl` only prints the default output columns i.e. `Name` and `Age`. The overall intention is to start adding more output in the `kubectl get` commands to provide more info on the state of the CR and this issue is the first one in that direction.

>how will adding the namespace column be helpful?

Even when the CRDs are namespaced scope, we don't see the NAMESPACE column in the `kubectl get` output. This info might be useful for platform operators with cluster-wide permissions.

**Comment by shubham14bajpai** [comment]
Yes makes sense, I was able to do the same but the output made me curious. With namespaced CRDs the output of 
`kubectl get byocluster` would give only the CRs in `default` namespace only so the `NAMESPACE` column will have the same value we pass in the namespace flag. 
```
$ kubectl get byocluster 
NAME                NAMESPACE   AGE
byocluster-sample   default     81m
$ kubectl get byocluster -n test
NAME                NAMESPACE   AGE
byocluster-sample   test        37m

```

**Comment by dharmjit** [comment]
> With namespaced CRDs the output of
> `kubectl get byocluster` would give only the CRs in `default` namespace

That is the default behavior that will query only the default namespace. Could you check the output for `kubectl get byoclusters -A`?

**Comment by shubham14bajpai** [comment]
> > With namespaced CRDs the output of
> > `kubectl get byocluster` would give only the CRs in `default` namespace
> 
> That is the default behavior that will query only the default namespace. Could you check the output for `kubectl get byoclusters -A`?

Kubernetes handles this case and we are getting two `NAMESPACE` columns

```
$ kubectl get byocluster -A
NAMESPACE   NAME                NAMESPACE   AGE
default     byocluster-sample   default     91m
test        byocluster-sample   test        47m

```
