### ISSUE TITLE
Update installer cli to indicate correct support matrix

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#414]
**Describe the solution you'd like**
Current output of listing supported OS and K8s version
```
$ ./cli --list-supported
OS			K8S Version	BYOH Bundle Name
---			-----------	----------------
Ubuntu_20.04.1_x86-64	 v1.22.3	byoh-bundle-ubuntu_20.04.1_x86-64_k8s_v1.22.3
```

- We need to update the OS support to indicate `Ubuntu 20.04.*`
- After #411, we will be flexible enough to support any version in a given minor series. So the K8s version column should read `v1.22.*`. The output should contain a message saying the corresponding bundles (particular to a patch version) should be pushed to the OCI registry of choice. By default, BYOH uses [projects.registry.vmware.com](https://projects.registry.vmware.com/)
- Similarly, the BYOH Bundle Name also needs to be updated.
- Update [local-dev.md](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/local_dev.md#cli) guide to reflect the changes.

**Anything else you would like to add:**
While we may have to wait for #411 to be completed to update K8s version column, in the meantime (as part of a different PR), update the OS column

**Comment by dharmjit** [comment]
Closing this as it was fixed in this PR #437
