### ISSUE TITLE
Enable feature gate for secure access

### ISSUE THREAD

**Issue by NilanjanDaw** [vmware-tanzu/cluster-api-provider-bringyourownhost#428]
**Describe the solution you'd like**
Add a feature gate flag called `SecureAccess` to enable bootstrap-token based cluster access for BYOH

**Comment by NilanjanDaw** [comment]
Discussion thread for task:
Prevent `host registration` if `SecureAccess` is enabled and instead depend on the `ByoAdmission Controller` to perform the registration. 

Part of the current registration process also involves setting up the network interfaces:
https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/cc9ae9bda980f2a119b494e4caf518b475151186/agent/registration/host_registrar.go#L67

This in turn is required in the`bootstrapK8sNode` process as part of `reconcileNormal`:
https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/cc9ae9bda980f2a119b494e4caf518b475151186/agent/main.go#L180-L191

https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/cc9ae9bda980f2a119b494e4caf518b475151186/agent/reconciler/host_reconciler.go#L247-L254

Should we refactor the registration process and separate the network interface setup? @anusha94 @dharmjit wdyt?
cc @sachinkumarsingh092

**Comment by NilanjanDaw** [comment]
> In my mind the ByoHost registration will still be part of the agent reconciler but we will be blocking it in case SecureAccess feature flag is enabled till it finds the kubeconfig in the required dir. Am I missing something?

I might be a bit confused, but I thought a minimal `ByoHost` will be registered by the Admission Controller once a CSR is approved.

**Comment by dharmjit** [comment]
> I thought a minimal `ByoHost` will be registered by the Admission Controller once a CSR is approved

oh okay, not sure why this is required but I thought Admission Controller is only to create Role/RoleBinding. 
cc: @anusha94

**Comment by anusha94** [comment]
> Should we refactor the registration process and separate the network interface setup?

We should eventually decouple this because the `Admission Controller` will only create a basic CRD with name and namespace. Updating labels and network interface can be part of `host_reconciler`.
For this PR, we don't need to do this. We only have to see if feature-flag or env variable is set.
If `SecureAccess` is true, skip registration.

**Comment by NilanjanDaw** [comment]
> For this PR, we don't need to do this. We only have to see if feature-flag or env variable is set.
If SecureAccess is true, skip registration.

I think the skip-registration will require some refactoring, since there are some dependencies between the registration process and starting the reconciler.

**Comment by anusha94** [comment]
For env variables - see `CLUSTER_TOPOLOGY` in CAPI
https://github.com/kubernetes-sigs/cluster-api/search?q=CLUSTER_TOPOLOGY
