### ISSUE TITLE
Add Host platform related fields to ByoHost CRD

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#469]
Improve `ByoHost`CRD to include host platform details such as Operating System, Architecture, etc. In this issue, we could also discuss what all fields could be added and where it makes sense to keep this information(`Spec`, `Status`).

**Comment by sachinkumarsingh092** [comment]
@dharmjit do we have some docs or some previous discussions around these details?

**Comment by anusha94** [comment]
@sachinkumarsingh092 No. Hoping to initiate the conversation with this issue :)

**Comment by sachinkumarsingh092** [comment]
Let's take a crude example of what all details are generally stored on a typical host. If, for example, the host is an EC2 instance, it has the following instance information:
```
"IsLatestVersion": false, 
"ComputerName": "ip-172-31-39-244.ec2.internal", 
"PingStatus": "Online", 
"InstanceId": "i-0b89uiydekijihuh", 
"IPAddress": "172.31.39.244", 
"ResourceType": "EC2Instance", 
"AgentVersion": "2.3.978.0", 
"PlatformVersion": "20.04", 
"PlatformName": "Ubuntu", 
"PlatformType": "Linux", 
"LastPingDateTime": 1593669078.246
```
Although these are probably not platform-agnostic details, I think we can use them as references.

We already have all the [network information](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/apis/infrastructure/v1beta1/byohost_types.go#L49) of the host. We can extend `ByoHostStatus` to include the following:
- OS Name
- OS version
- Architecture type
-  Host Name or ID (if required)

We can create a new field, let's say, `HostRef` in `ByoHostStatus` and a new type `HostStatus` to have all this information.

WDYT? @dharmjit @anusha94

**Comment by shubham14bajpai** [comment]
What about taking inspiration from this [NodeSystemInfo](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L4185) field we have in k8s Node status? And if all fields are applicable we can just embed this itself.

**Comment by sachinkumarsingh092** [comment]
Oh, great! Didn't knew about this. So much to learn. Seems like just the thing that we want. So we can just use this in `ByoHostStatus` instead of creating a new type.

**Comment by dharmjit** [comment]
I agree that we have to keep it extensible for plugging more host info in the future, but IMO below is important as @sachinkumarsingh092 has suggested for now.
- OS Name
- OS version
- Architecture type
- Host Name or ID (if required)

> We can create a new field, let's say, HostRef in ByoHostStatus and a new type HostStatus to have all this information.

make sense. We could have `HostInfo` type in `HostStatus`

> What about taking inspiration from this [NodeSystemInfo](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L4185) field

Some of the information will not be available at the time of host registration and in my mind replicating the NodeInfo in ByoHost is not required.

**Comment by shubham14bajpai** [comment]
>Some of the information will not be available at the time of host registration and in my mind replicating the NodeInfo in ByoHost is not required.

Okay if only a small set of fields overlap between them then this makes more sense 👍
