### ISSUE TITLE
Add ByoHost CR with the Host platform information

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#470]
After #469, we need to add the host platform details while registering `ByoHost` CR in the Host-Agent.

**Comment by shubham14bajpai** [comment]
@dharmjit @anusha94 For this do we need to write an interface for different OS (linux, windows) to be future ready or 
we can just go ahead with linux for now and make it logic independent later as we start supporting more OS? 
Also should the agent fail if it detects an unsupported OS/Arch?

**Comment by sachinkumarsingh092** [comment]
I think this is a good idea to be future-proof this way, but everything now is based on the assumption of the OS being an Ubuntu Linux. The current [os-detection for the agent](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/agent/installer/os_detector.go) (which is a good reference for this task) assumes this only.

What we can do for this task, is to follow the trend and do this for Ubuntu Linux for now. Later on, we can make a task/effort to have these interfaces for every logic for os detection. This way it would be a uniform and consistent change throughout the codebase.

> Also should the agent fail if it detects an unsupported OS/Arch?

We can have similar logic or even modularise this logic out of the installer to be reused in both the [installer](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/tree/main/agent/installer) and during [registration](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/agent/registration/host_registrar.go).

What do you folks think?

**Comment by dharmjit** [comment]
Hi @shubham14bajpai @Sachin, I would suggest that we should at least target Linux-based Operating systems. I tried to look at how the `kubelet` is fetching this information and it uses goruntime `GOOS`, `GOARCH` fields for OS/Arch and for the OSImage we can use /etc/os-release(I think this is a standardized file across Linux system but you could double-check on this.)

**Comment by shubham14bajpai** [comment]
> Hi @shubham14bajpai @sachin, I would suggest that we should at least target Linux-based Operating systems. I tried to look at how the `kubelet` is fetching this information and it uses goruntime `GOOS`, `GOARCH` fields for OS/Arch and for the OSImage we can use /etc/os-release(I think this is a standardized file across Linux system but you could double-check on this.)

Yes I was looking at the same as the [runtime](https://pkg.go.dev/runtime#pkg-constants) package provides us with the details very easily. I guess we don't need the interfaces right now as there is no talk on windows support. Will proceed with the above approach then.

**Comment by DavidSpek** [comment]
I’m not sure how relevant this will be for this infrastructure provider, but it might also be nice to implement https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210310-opt-in-autoscaling-from-zero.md since the given node information can also be useful elsewhere.
