### ISSUE TITLE
[Docs] Add OS and k8s compatibility matrix in README

### ISSUE THREAD

**Issue by sachinkumarsingh092** [vmware-tanzu/cluster-api-provider-bringyourownhost#478]
Earlier BYOH supported only a single version of Ubuntu and k8s. But now we support multiple versions of these.
[Here](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/local_dev.md#supported-os-and-kubernetes
) is the list of supported OS and k8s versions.

We want the README to have a section like [this ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere#compatibility-with-cluster-api-and-kubernetes-versions)section in CAPV.

**Comment by VibhorChinda** [comment]
@sachinkumarsingh092 can I work on this ?? :))

**Comment by sachinkumarsingh092** [comment]
Sure, go ahead! Thanks for doing this.

/assign @VibhorChinda

**Comment by sachinkumarsingh092** [comment]
Merged #488
