### ISSUE TITLE
Create installation / uninstallation scripts from agent installer algo

### ISSUE THREAD

**Issue by mayur-tolexo** [vmware-tanzu/cluster-api-provider-bringyourownhost#486]
Create `installation` / `uninstallation` scripts from agent installer [algo](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/agent/installer/internal/algo/ubuntu20_4K8s1_22.go).    
We will be storing this algo as bash script and the new installer controller in #467 will be using these scripts to create the installation secret.

**Comment by mayur-tolexo** [comment]
@anusha94 @dharmjit , 
Where should we store these scripts? in `./scripts`?

**Comment by dharmjit** [comment]
Not sure of the benefits of keeping it external as bash scripts, I would prefer to keep these scripts as variables/constants inside the installer controller code itself. @anusha94 WDYT?

**Comment by mayur-tolexo** [comment]
Ok then should I create these variables in [algo](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/tree/main/agent/installer/internal/algo) itself and later we can import it in `K8sInstallerConfig` controller.
