### ISSUE TITLE
[Feature] Cluster Class support in BYOH

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#487]
As a cluster operator, if I want to create a workload cluster then I need to create a bunch of underlying resources such as KCP, MachineDeployments, and infrastructure or bootstrap templates for those resources which logically end up representing the cluster. Similarly if I want to create 100 similar clusters then every time I need to create the same type of resources but with different cluster specific values like name, etc. 

And not only this, in case the user wants to upgrade the kubernetes version or wants to update replica count then he/she has to update at all the places one by one because ​​the cluster configuration is spread around multiple components, and upgrading the version is hard as it requires changes to different fields in different resources. And this is a very tedious process and opens a lot of room for error.

We need a way through which we can create multiple clusters of similar shape without duplication and could easily configure cluster variables. So to achieve this flexibility, we can use CAPI’s Cluster Class feature.

To know more about, go through this [documentation](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210526-cluster-class-and-managed-topologies.md).

### Why do we need to extend ClusterClass support in BYOH?
Before Cluster Class, Cluster API did not expose a native way to provision multiple clusters of the same configuration and it was very complex to alter the cluster configurations like scaling of the nodes, adding/removing sets of worker nodes and upgrading cluster kubernetes versions. 

With the help of cluster class support, we can provision multiple BYO clusters of similar flavor. As BYOCluster is a cluster on a bare metal so we might not see multiple flavors like we have with other cloud providers (AWS and Azure). But we can leverage the Cluster class, to create multiple clusters of similar shape.

Also if we use cluster class to provision the cluster, then it would act as a single control point for the entire cluster. Scaling the nodes, adding/removing sets of worker nodes and upgrading cluster kubernetes versions would be achievable by editing the topology. This would facilitate the maintenance of existing clusters as well as ease the creation of newer clusters.

### Tracking Issues

**Comment by shivi28** [comment]
@anusha94 I will take this and add the tracking issues. But unable to assign it 
/assign @shivi28

**Comment by shivi28** [comment]
This feature is done, so marking this close
