### ISSUE TITLE
Create a new API of kind K8sInstallerConfig

### ISSUE THREAD

**Issue by mayur-tolexo** [vmware-tanzu/cluster-api-provider-bringyourownhost#489]
Create a new API of kind `K8sInstallerConfig` with CRD having following types:
- Must have a spec field with the following:
  - BundleRepo (string): Registry from which bundle will be downloaded
  - BundleType (string): type of the bundle (e.g. vanilla-k8s, k3s) need to be downloaded
- Must have a status field with the following:
  - Ready (boolean): indicates the installation secret has been generated and is ready
  - InstallationSecret (ObjectReference): installation secret object reference

This API should be in `infrastructure` group and `v1beta1` version

**Comment by shamsher31** [comment]
> This API should be in infrastructure group and v1beta1 version

@mayur-tolexo API version should be `v1aplha1`?

**Comment by mayur-tolexo** [comment]
@shamsher31, I thought it will be created in the same version as of other apis of byo.

**Comment by shamsher31** [comment]
> @shamsher31, I thought it will be created in the same version as of other apis of byo.

I see, if the BYO API version is `v1beta1` then we need to use the same.
