### ISSUE TITLE
Fix local development doc cluster-template.yaml location

### ISSUE THREAD

**Issue by mayur-tolexo** [vmware-tanzu/cluster-api-provider-bringyourownhost#511]
**What steps did you take and what happened:**
cluster-template file used for local development has been moved to [test/e2e/data/infrastructure-provider-byoh/v1beta1/templates/docker](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/tree/main/test/e2e/data/infrastructure-provider-byoh/v1beta1/templates/docker). So, the [local development doc ](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/local_dev.md#create-docker-hosts)need to be updated from
```sh
cat test/e2e/data/infrastructure-provider-byoh/v1beta1/cluster-template.yaml | envsubst | kubectl apply -f -
```
to 
```sh
cat test/e2e/data/infrastructure-provider-byoh/v1beta1/templates/docker/cluster-template.yaml | envsubst | kubectl apply -f -
```

**Comment by VibhorChinda** [comment]
Can I work on this ??
@sachinkumarsingh092 @mayur-tolexo
