### ISSUE TITLE
Remove BundleLookupTag from the ByoClusterSpec

### ISSUE THREAD

**Issue by dharmjit** [vmware-tanzu/cluster-api-provider-bringyourownhost#567]
Initially `BundleLookupTag` field was introduced in the [ByoClusterSpec](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/apis/infrastructure/v1beta1/byocluster_types.go#L30) as the BYOH Bundle OCI image tagging uses the `BYOH` release versioning scheme. Now the Bundle tags use the K8s version in the OCI image tag for e.g. `byoh-bundle-ubuntu_20.04.1_x86-64_k8s:v1.23.5`, hence we can remove the field and refactor the code to use K8s version.

**Comment by Ankitasw** [comment]
Is it ok if I pick this issue?
