### ISSUE TITLE
[WIP] [UX experience] Merge clusterclass and cluster topology yaml into a single file for all packages

### ISSUE THREAD

**Issue by shivi28** [vmware-tanzu/cluster-api-provider-bringyourownhost#643]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in implementing the feature.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

**Comment by anusha94** [comment]
Why is this needed? What better UX do we achieve?
