### ISSUE TITLE
Support for Kubernetes 1.24

### ISSUE THREAD

**Issue by anusha94** [vmware-tanzu/cluster-api-provider-bringyourownhost#677]
**Describe the solution you'd like**
The latest K8s release being `1.24.3` (https://kubernetes.io/releases/), we should support v1.24 minor series and update our e2e tests to be at par with the greatest minor release available.

**Anything else you would like to add:**
Update README and other relevant documents regarding K8s version support

**Comment by shivi28** [comment]
Adding support for K8s v1.24.6
