### ISSUE TITLE
Other linux distributions and support for ubuntu versions?

### ISSUE THREAD

**Issue by keshavcruise** [vmware-tanzu/cluster-api-provider-bringyourownhost#770]
Hi I have a question about compatibility other than Linux 20.04. I have seen similar issues mentioning 22.04 will be tested soon soon, has this happened yet? 

I'm also curious as to what is limiting BYOH to ubuntu? I see a [DoUbuntu20_4K8s1_22](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/installer/internal/algo/ubuntu20_4k8s.go#L69) install script in the repo. Is this what limits support to ubuntu or are there any other dependencies? Would other debian based distributions be a safe bet? Was this an administrative decision to limit maintenance/testing overhead? I'm trying to understand  what the limiting factors are here before using it more widely.

I've tried it out and love it's simplicity compared to other infrastructure providers!

**Comment by dharmjit** [comment]
Hi @keshavcruise, the current installer interface is extensible and we could extend support for various OS. [internal/algo](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/tree/main/installer/internal/algo) could have implementations for other OS/Versions. We would be happy to accept any community contributions to enable support for other OSes.

Note that, if you have other means of installing the K8s components in your hosts, you could also use `--skip-installation` flag to skip the installer completely.

**Comment by knfoo** [comment]
Can you describe how to do this ?
I would like to add support for Debian

**Comment by keshavcruise** [comment]
@knfoo This can be done by passing `--skip-installation` flag while starting your host agent

**Comment by knfoo** [comment]
@keshavcruise I guess I was unclear I already use `--skip-installation` to run on Debian.
I am more interested in some instructions on how to create the logic to support Debian via the https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/tree/main/installer/internal/algointernal/algo that @dharmjit mentioned.

When looking at the ubuntu20_4k8s.go file it looks like it expects that a bundle is stored somewhere outside this repo (github.com/vmware-tanzu/carvel-imgpkg/releases/download/$IMGPKG_VERSION/imgpkg-linux-$ARCH).
So I am asking about how to contribute to this flow and create bundle for a different OS.

**Comment by dharmjit** [comment]
Hi @knfoo, You are correct that we need to create a new carvel imgpkg bundle for supporting a new OS/version and this bundle needs to be published in OCI registry. The code for the same is in https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/tree/main/installer/bundle_builder. I think that the bundle for Ubuntu 20.04 and Ubuntu 22.04 will be same and we could just rename the same bundle.
