### ISSUE TITLE
Does byoh support Rocky Linux?

### ISSUE THREAD

**Issue by sudharsanomprakash** [vmware-tanzu/cluster-api-provider-bringyourownhost#796]
**What steps did you take and what happened:**
Trying to deploy k8s 1.24.2 and got below error

E0427 01:41:16.608283 1 k8sinstallerconfig_controller.go:154] controller/k8sinstallerconfig "msg"="failed to create installer instance" "error"="No k8s support for OS" "architecture"="amd64" "byoMachine"="byoh-cluster-control-plane-m89ed" "cluster"="byoh-cluster" "k8sVersion"="v1.24.2" "name"="byoh-cluster-control-plane-m89ed" "namespace"="default" "osImage"="Rocky Linux 9.1 (Blue Onyx)" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="K8sInstallerConfig"

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`): 
- OS (e.g. from `/etc/os-release`): Rocky Linux 9.1 (Blue Onyx)

**Comment by dharmjit** [comment]
Hey @sudharsanomprakash, Thanks for trying out `BYOH`. As of today, `BYOH` only supports Ubuntu 20.04.
