### ISSUE TITLE
Add support for K8s version v1.26.x

### ISSUE THREAD

**Issue by steve-fraser** [vmware-tanzu/cluster-api-provider-bringyourownhost#797]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

I would like to use k8s version 1.26.x with BOYH

**Anything else you would like to add:**
[Miscellaneous information that will assist in implementing the feature.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

**Comment by oingooing** [comment]
i want too!
