### ISSUE TITLE
byoh agent launch error "error"="cannot create certificate signing request: Unauthorized"

### ISSUE THREAD

**Issue by phamquy** [vmware-tanzu/cluster-api-provider-bringyourownhost#817]
**What steps did you take and what happened:**
I follow the instruction from this link https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/blob/main/docs/getting_started.md with the following setup

- Create a management K8s cluster on 3 EC2 instances 
- Deploy Boyh cluster api component on my management cluster 
- Create 3 Ubuntu 20.04 instance as boyh hosts
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Start agent in the 3 byoh 
```
sudo ./byoh-hostagent-linux-amd64 --bootstrap-kubeconfig bootstrap-kubeconfig.conf
```
confirm that three hosts are picked up by cluster api 
```
~/capi kubectl get byohosts                                                                                             05:19:13
NAME              OSNAME   OSIMAGE              ARCH
ip-172-31-4-123   linux    Ubuntu 20.04.6 LTS   amd64
ip-172-31-6-20    linux    Ubuntu 20.04.6 LTS   amd64
ip-172-31-8-92    linux    Ubuntu 20.04.6 LTS   amd64
```

- Terminate and delete a host from the list 
`kubectl delete byohosts ip-172-31-6-20`

- COnfirm the list 
```
kubectl get byohosts                                                                                             17:25:23
NAME              OSNAME   OSIMAGE              ARCH
ip-172-31-4-123   linux    Ubuntu 20.04.6 LTS   amd64
ip-172-31-8-92    linux    Ubuntu 20.04.6 LTS   amd64
```

- Launch other instance and install require apps and edit `ect/hosts/` to add map 127.0.0.1 to hostname
- download [byoh-hostagent-linux-amd64](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/v0.3.0/byoh-hostagent-linux-amd64) and copy same bootstrap kubeconfig from the other two byoh
- Start agent, and see error
```
sudo ./byoh-hostagent-linux-amd64 --bootstrap-kubeconfig bootstrap-kubeconfig.conf
I0630 17:28:21.473699    1937 main.go:230]  "msg"="initiated bootstrap kubeconfig flow"
I0630 17:28:21.475611    1937 csr.go:120]  "msg"="certTimeToExpire" "duration"=31536000000000000
E0630 17:28:21.482476    1937 csr.go:129]  "msg"="in request certificate" "error"="cannot create certificate signing request: Unauthorized"
E0630 17:28:21.482511    1937 main.go:161]  "msg"="bootstrap flow failed" "error"="kubeconfig generation failed: cannot create certificate signing request: Unauthorized"
```
**What did you expect to happen:**
Agent started and the new host listed in mgmt cluster 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
```
clusterctl version: &version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3", GitCommit:"14b88ca091102b72c591cb0357199834385df478", GitTreeState:"clean", BuildDate:"2023-06-06T15:41:40Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version: (use `kubectl version --short`):
```
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.24.0
```
- OS (e.g. from `/etc/os-release`): 
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by dharmjit** [comment]
As per the slack convo[[here](https://kubernetes.slack.com/archives/C8TSNPY4T/p1687678256634439)], It seems like you are past this error. Please feel free to close this if you are not facing the issue anymore.
